import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface InvoicePdfData {
  tenant: { nameAr: string; nameEn: string; taxNumber?: string | null; commercialReg?: string | null; governorate?: string | null; phone?: string | null; address?: string | null };
  invoice: {
    number: string;
    date: Date;
    dueDate?: Date | null;
    contactName: string;
    contactTaxNumber?: string | null;
    currency: string;
    subtotal: string;
    taxTotal: string;
    discountTotal?: string;
    total: string;
    notes?: string | null;
    kind: string;
    hsCode?: string | null;
    countryOfOrigin?: string | null;
  };
  lines: Array<{
    description: string;
    quantity: string;
    unitOfMeasure?: string;
    unitPrice: string;
    taxRate: string;
    lineTotal: string;
  }>;
  locale: 'ar' | 'ku' | 'en';
}

export function buildInvoicePdf(data: InvoicePdfData): Buffer {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const isRtl = data.locale === 'ar' || data.locale === 'ku';
  const W = doc.internal.pageSize.getWidth();
  const M = 40;

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(data.tenant.nameEn, isRtl ? W - M : M, 60, { align: isRtl ? 'right' : 'left' });
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  if (data.tenant.taxNumber) doc.text(`TIN: ${data.tenant.taxNumber}`, isRtl ? W - M : M, 78, { align: isRtl ? 'right' : 'left' });
  if (data.tenant.commercialReg) doc.text(`CR: ${data.tenant.commercialReg}`, isRtl ? W - M : M, 92, { align: isRtl ? 'right' : 'left' });
  if (data.tenant.governorate) doc.text(data.tenant.governorate, isRtl ? W - M : M, 106, { align: isRtl ? 'right' : 'left' });

  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  const title = data.invoice.kind === 'CREDIT_NOTE' ? 'CREDIT NOTE' :
                data.invoice.kind === 'DEBIT_NOTE'  ? 'DEBIT NOTE'  :
                data.invoice.kind === 'EXPORT'      ? 'EXPORT INVOICE' :
                data.invoice.kind === 'IMPORT'      ? 'IMPORT INVOICE' : 'INVOICE';
  doc.text(title, isRtl ? M : W - M, 60, { align: isRtl ? 'left' : 'right' });
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`# ${data.invoice.number}`, isRtl ? M : W - M, 78, { align: isRtl ? 'left' : 'right' });
  doc.text(`Date: ${data.invoice.date.toISOString().slice(0, 10)}`, isRtl ? M : W - M, 92, { align: isRtl ? 'left' : 'right' });
  if (data.invoice.dueDate) doc.text(`Due: ${data.invoice.dueDate.toISOString().slice(0, 10)}`, isRtl ? M : W - M, 106, { align: isRtl ? 'left' : 'right' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', M, 150);
  doc.setFont('helvetica', 'normal');
  doc.text(data.invoice.contactName, M, 166);
  if (data.invoice.contactTaxNumber) doc.text(`TIN: ${data.invoice.contactTaxNumber}`, M, 180);

  autoTable(doc, {
    startY: 210,
    head: [['Description', 'Qty', 'UoM', 'Unit Price', 'Tax %', 'Line Total']],
    body: data.lines.map((l) => [
      l.description,
      l.quantity,
      l.unitOfMeasure ?? 'PCS',
      l.unitPrice,
      `${(parseFloat(l.taxRate) * 100).toFixed(2)}%`,
      l.lineTotal,
    ]),
    styles: { fontSize: 10, cellPadding: 6 },
    headStyles: { fillColor: [34, 87, 75], textColor: 255, fontStyle: 'bold' },
    columnStyles: {
      1: { halign: 'right' },
      3: { halign: 'right' },
      4: { halign: 'right' },
      5: { halign: 'right' },
    },
  });

  const finalY = (doc as any).lastAutoTable?.finalY ?? 300;
  const right = W - M;
  let y = finalY + 24;
  doc.setFont('helvetica', 'normal');
  doc.text(`Subtotal: ${data.invoice.subtotal} ${data.invoice.currency}`, right, y, { align: 'right' });
  y += 16;
  if (data.invoice.discountTotal && parseFloat(data.invoice.discountTotal) > 0) {
    doc.text(`Discount: ${data.invoice.discountTotal} ${data.invoice.currency}`, right, y, { align: 'right' });
    y += 16;
  }
  doc.text(`Tax: ${data.invoice.taxTotal} ${data.invoice.currency}`, right, y, { align: 'right' });
  y += 16;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(`Total: ${data.invoice.total} ${data.invoice.currency}`, right, y, { align: 'right' });

  if (data.invoice.notes) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.text(data.invoice.notes, M, y + 30, { maxWidth: W - M * 2 });
  }

  const pageH = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(
    'Generated by Iraq ERP · iraqerp.app',
    W / 2,
    pageH - 24,
    { align: 'center' }
  );

  const out = doc.output('arraybuffer');
  return Buffer.from(out);
}

export interface PayslipPdfData {
  tenant: { nameEn: string; nameAr: string; taxNumber?: string | null };
  employee: { empNo: string; fullNameEn: string | null; fullNameAr: string; nationalId?: string | null; jobTitle?: string | null };
  period: string;
  line: {
    baseSalary: string;
    allowances: string;
    overtime: string;
    bonuses: string;
    gross: string;
    ssEmployee: string;
    incomeTax: string;
    otherDeductions: string;
    net: string;
  };
  currency: string;
}

export function buildPayslipPdf(data: PayslipPdfData): Buffer {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const M = 40;

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(data.tenant.nameEn, M, 60);
  doc.setFontSize(16);
  doc.text(`Payslip · ${data.period}`, W - M, 60, { align: 'right' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Employee No: ${data.employee.empNo}`, M, 110);
  doc.text(`Name: ${data.employee.fullNameEn ?? data.employee.fullNameAr}`, M, 126);
  if (data.employee.nationalId) doc.text(`National ID: ${data.employee.nationalId}`, M, 142);
  if (data.employee.jobTitle) doc.text(`Position: ${data.employee.jobTitle}`, M, 158);

  autoTable(doc, {
    startY: 190,
    head: [['Earnings', 'Amount', '', 'Deductions', 'Amount']],
    body: [
      ['Base Salary',    `${data.line.baseSalary} ${data.currency}`,  '', 'Social Security (5%)', `${data.line.ssEmployee} ${data.currency}`],
      ['Allowances',     `${data.line.allowances} ${data.currency}`,  '', 'Income Tax (PIT)',     `${data.line.incomeTax} ${data.currency}`],
      ['Overtime',       `${data.line.overtime} ${data.currency}`,    '', 'Other Deductions',     `${data.line.otherDeductions} ${data.currency}`],
      ['Bonuses',        `${data.line.bonuses} ${data.currency}`,     '', '',                     ''],
      ['Gross', `${data.line.gross} ${data.currency}`, '', 'Total Deductions',
        `${(parseFloat(data.line.ssEmployee) + parseFloat(data.line.incomeTax) + parseFloat(data.line.otherDeductions)).toFixed(2)} ${data.currency}`],
    ],
    styles: { fontSize: 10, cellPadding: 6 },
    headStyles: { fillColor: [34, 87, 75], textColor: 255 },
  });

  const finalY = (doc as any).lastAutoTable?.finalY ?? 400;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setDrawColor(34, 87, 75);
  doc.setFillColor(240, 248, 244);
  doc.rect(M, finalY + 20, W - M * 2, 50, 'FD');
  doc.text(`NET PAY: ${data.line.net} ${data.currency}`, W / 2, finalY + 52, { align: 'center' });

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(
    'This payslip is computed under Iraqi Labor Law and General Commission for Taxes rules.',
    W / 2,
    finalY + 100,
    { align: 'center' }
  );

  const out = doc.output('arraybuffer');
  return Buffer.from(out);
}
